### ISSUE TITLE
Searching the Forest

### ISSUE THREAD

**Issue by porkbob** [Kyuuhachi/Azure-Vitality#7]
For quest 3:

- When you reach the previous boss area and wake up the guardsman, no music plays. I assume this is another instance where you need to do the workaround.

- I'm assuming mireille isn't meant to appear as a guest npc in battle, But if she is it isn't working

Other than those, just grammatical things:

- In the beginning Randy says "That kind of problems happen all the time" instead of 'These kind'

- At object 8 when they split up for a cutscene, Lloyd says "Let's not go farther than so we can still see each other". It's not exactly great English. I'm not sure what the JP text was, but "Let's stay close enough so we can still see each other" would be much better.

- Same scene shortly after, Randy says "I don't know about Mishelam, but the CGF don't have anything to do in a shopping center, do you?" I'm not sure how to make it make sense while keeping the way it's structured, but "I don't know about Mishelam, but what would the CGF need to do in a shopping center?" would be a lot clearer to me.
*personal note*: The whole exchange between Mireille and Randy in this cutscene seems very "direct-translate-y"—like stiff, awkward, and not flowing well or seeming like a real conversation at all. But just seeing the text as-is, I wouldn't know how to clean it up without just making assumptions about how it should flow. Not necessarily suggesting you do something about it, but just my thoughts.

**Comment by Kyuuhachi** [comment]
Looking at the Evo script, I don't think the missing music is a bug; there is a command to fade out the music, but none to start any new one. The weird thing is that there's another `BgmStop` command later in the same scene, even though it doesn't play anything. So it's possible that there is a bug, but if so, that is in Evo too.

And no, Mireille doesn't participate in battle.

That particular scene was really hard to translate, in part because I didn't remember how their relationship is at that part of the game. And yeah, that particular line I got all wrong: she's talking about *next* time they're out together. I tweaked it a bit so it sounds at least a little more natural, I think (you can check the [diff](https://github.com/Kyuuhachi/Azure-Vitality/commit/d66870a101194f4668f72c604a566f23d8aafce1)). If you have any suggestions I'd be glad to hear.

I think the first two points are a WONTFIX though.

**Comment by porkbob** [comment]
The changes look excellent. You even included some exact phrasing I had thought about but not typed up in the report lol. This is the only evo quest so far in both games where I was getting taken out of the conversations by their wording, so I believe this will help considerably.

As far as their relationship at this point, in the intermission Randy bought her a necklace in the expensive store and gave it to her offscreen sometime. NPC dialogue after that shows her slipping up and letting on that she treasures it, but then being tsundere and acting like she doesn't care about it. While Randy clearly does think of her as special to him based on buying the gift, he also seems to be in denial—whether just pretending, or wanting to be able to flirt freely with anyone, or just being afraid of attachment. Also other party members clearly see what they have and a couple have previously said that Randy shouldn't take her for granted, in different ways.

So I would say they are at the last millimeter or so from being official at this point. I haven't done all the NPC dialogue in this playthrough, but I did the first time I played. But yeah... based on Zero, the CD drama, and Azure so far—that pretty much sums it up.

**Comment by porkbob** [comment]
And as far as the bgm, it's not as long and awkward as the Arseille scene in the previous quest, but it seems likely there should have been something playing there. Usually no music is meant for creepy or uneasy moments, not "we saved him and he's okay". I don't really feel like looking through the track list and pinpointing which was most appropriate right now though, so it'll have to do.
